name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  env:
    MONGO_DB_URL: ${{secrets.MONGO_DB_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "16.x"

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test
      
  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "samuel-shyaka-my-brand"
            heroku_email: "samyshyaka@gmail.com"
